name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # dotnet is already installed from the previous step, so we can just run
      - name: Restore dependencies
        run:  dotnet restore ./ci-cd_OG/ci-cd_OG.sln

      - name: Build App
        run: dotnet build -c Release --no-restore ./ci-cd_OG/ci-cd_OG.sln

   #   - name: Automated Tests
   #     run: dotnet test Weather.Tests -c Release --no-build

      - name: Publish App
        run: dotnet publish -c Release -o ./out ./ci-cd_OG/ci-cd_OG.sln
  